#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if ! command -v sbatch >/dev/null 2>&1; then
  echo "ERROR: sbatch not found. Run this on the HPC login node."
  exit 1
fi

if [ -z "${ROUGH_CKPT:-}" ]; then
  echo "ERROR: ROUGH_CKPT is required."
  echo "Try:"
  echo "  export ROUGH_CKPT=\"$(cd "${ROOT_DIR}" && pwd)/mujoco_playground/logs/<rough_run>/checkpoints/<step_dir>\""
  exit 1
fi

MODE="${MODE:-ppo_dense}" # ppo_dense|maxrl_binary|maxrl_t
USE_CUDA="${USE_CUDA:-1}"
if [ "${USE_CUDA}" != "1" ]; then
  echo "ERROR: submit_push_recovery currently supports GPU path only (USE_CUDA=1)."
  exit 1
fi

case "${MODE}" in
  ppo_dense)
    SBATCH_SCRIPT="${ROOT_DIR}/slurm/g1_push_recovery_gpu.sbatch"
    ;;
  maxrl_binary)
    SBATCH_SCRIPT="${ROOT_DIR}/slurm/g1_push_maxrl_gpu.sbatch"
    ;;
  maxrl_t)
    SBATCH_SCRIPT="${ROOT_DIR}/slurm/g1_push_maxrl_t_gpu.sbatch"
    ;;
  *)
    echo "ERROR: invalid MODE=${MODE}. Expected ppo_dense|maxrl_binary|maxrl_t"
    exit 1
    ;;
esac

PARTITION="${PARTITION:-gpu}"
GPUS="${GPUS:-1}"
CPUS_PER_TASK="${CPUS_PER_TASK:-16}"
MEM="${MEM:-}"
TIME_LIMIT="${TIME_LIMIT:-24:00:00}"

EXPORT_VARS=(
  "ALL"
  "MODE=${MODE}"
  "ADV_MODE=${ADV_MODE:-}"
  "ROUGH_CKPT=${ROUGH_CKPT}"
  "ENV_NAME=${ENV_NAME:-G1JoystickRoughTerrain}"
  "NUM_ENVS=${NUM_ENVS:-1024}"
  "NUM_EVAL_ENVS=${NUM_EVAL_ENVS:-128}"
  "NUM_TIMESTEPS=${NUM_TIMESTEPS:-50000000}"
  "ENTROPY_COST=${ENTROPY_COST:-0.005}"
  "SEED=${SEED:-1}"
  "SUFFIX=${SUFFIX:-g1-push-${MODE}-seed${SEED:-1}}"
  "PLAYGROUND_CONFIG_OVERRIDES=${PLAYGROUND_CONFIG_OVERRIDES:-}"
  "SCENARIO_GROUP_SIZE=${SCENARIO_GROUP_SIZE:-8}"
  "MAXRL_LOG_ONLY=${MAXRL_LOG_ONLY:-0}"
  "MAXRL_SCENARIO_KEY=${MAXRL_SCENARIO_KEY:-push_cfg}"
  "MAXRL_VERBOSE=${MAXRL_VERBOSE:-1}"
  "PUSH_ADV_MASK_MODE=${PUSH_ADV_MASK_MODE:-off}"
  "PUSH_ADV_PRE_WEIGHT=${PUSH_ADV_PRE_WEIGHT:-0.1}"
  "PUSH_MASK_SOURCE=${PUSH_MASK_SOURCE:-chunk}"
  "PUSH_MASK_WINDOW_K=${PUSH_MASK_WINDOW_K:-20}"
  "PUSH_EVENT_EPS=${PUSH_EVENT_EPS:-1e-6}"
  "PUSH_ENTROPY_MODE=${PUSH_ENTROPY_MODE:-off}"
  "PUSH_ENTROPY_DELTA=${PUSH_ENTROPY_DELTA:-0.0}"
  "PUSH_REWARD_MODE=${PUSH_REWARD_MODE:-off}"
  "PUSH_REWARD_ABLATION_MODE=${PUSH_REWARD_ABLATION_MODE:-baseline}"
  "PUSH_INTERVAL_MIN=${PUSH_INTERVAL_MIN:-}"
  "PUSH_INTERVAL_MAX=${PUSH_INTERVAL_MAX:-}"
  "PUSH_MAGNITUDE_MIN=${PUSH_MAGNITUDE_MIN:-}"
  "PUSH_MAGNITUDE_MAX=${PUSH_MAGNITUDE_MAX:-}"
  "PUSH_DIRECTION_MODE=${PUSH_DIRECTION_MODE:-}"
  "PUSH_DIRECTION_FRAME=${PUSH_DIRECTION_FRAME:-}"
  "PUSH_BIASED_DIRECTION_PROB=${PUSH_BIASED_DIRECTION_PROB:-}"
  "PUSH_BIASED_DIRECTION_MIN_DEG=${PUSH_BIASED_DIRECTION_MIN_DEG:-}"
  "PUSH_BIASED_DIRECTION_MAX_DEG=${PUSH_BIASED_DIRECTION_MAX_DEG:-}"
  "PUSH_FIXED_ANGLE_DEG=${PUSH_FIXED_ANGLE_DEG:-}"
  "PUSH_SINGLE_PUSH=${PUSH_SINGLE_PUSH:-}"
  "SURVIVAL_ALIVE_SCALE=${SURVIVAL_ALIVE_SCALE:-1.0}"
  "SURVIVAL_TERMINATION_SCALE=${SURVIVAL_TERMINATION_SCALE:--100.0}"
  "SURVIVAL_ACTION_RATE_SCALE=${SURVIVAL_ACTION_RATE_SCALE:--0.0001}"
  "SURVIVAL_DOF_POS_LIMITS_SCALE=${SURVIVAL_DOF_POS_LIMITS_SCALE:--0.001}"
  "SURVIVAL_ANG_VEL_XY_SCALE=${SURVIVAL_ANG_VEL_XY_SCALE:--0.05}"
  "SURVIVAL_ORIENTATION_SCALE=${SURVIVAL_ORIENTATION_SCALE:--0.1}"
  "SURVIVAL_BASE_HEIGHT_SCALE=${SURVIVAL_BASE_HEIGHT_SCALE:--0.05}"
  "SURVIVAL_PHI_SCALE=${SURVIVAL_PHI_SCALE:-2.0}"
  "SURVIVAL_PHI_GAMMA=${SURVIVAL_PHI_GAMMA:-0.97}"
  "SURVIVAL_PHI_UPRIGHT_WEIGHT=${SURVIVAL_PHI_UPRIGHT_WEIGHT:-0.5}"
  "SURVIVAL_PHI_HEIGHT_WEIGHT=${SURVIVAL_PHI_HEIGHT_WEIGHT:-0.3}"
  "SURVIVAL_PHI_ANGVEL_WEIGHT=${SURVIVAL_PHI_ANGVEL_WEIGHT:-0.2}"
  "SURVIVAL_PHI_HEIGHT_MIN=${SURVIVAL_PHI_HEIGHT_MIN:-0.3}"
  "SURVIVAL_PHI_HEIGHT_NOMINAL=${SURVIVAL_PHI_HEIGHT_NOMINAL:-0.5}"
  "SURVIVAL_PHI_ANGVEL_K=${SURVIVAL_PHI_ANGVEL_K:-1.0}"
  "RECOVERY_GATED_ORIENTATION_SCALE=${RECOVERY_GATED_ORIENTATION_SCALE:-0.2}"
  "RECOVERY_GATED_BASE_HEIGHT_SCALE=${RECOVERY_GATED_BASE_HEIGHT_SCALE:-0.5}"
  "RECOVERY_WINDOW_K=${RECOVERY_WINDOW_K:-60}"
  "RECOVERY_WINDOW_TRACKING_SCALE=${RECOVERY_WINDOW_TRACKING_SCALE:-0.2}"
  "RECOVERY_OMEGA_WEIGHT=${RECOVERY_OMEGA_WEIGHT:-0.05}"
  "RECOVERY_BONUS=${RECOVERY_BONUS:-8.0}"
  "RECOVERY_BONUS_STABILITY_STEPS=${RECOVERY_BONUS_STABILITY_STEPS:-10}"
  "RECOVERY_BONUS_DELAY_STEPS=${RECOVERY_BONUS_DELAY_STEPS:-10}"
  "RECOVERY_STABLE_LIN_MIN=${RECOVERY_STABLE_LIN_MIN:-0.7}"
  "RECOVERY_STABLE_ANG_MIN=${RECOVERY_STABLE_ANG_MIN:-0.7}"
  "CAPTURE_POINT_LOG=${CAPTURE_POINT_LOG:-0}"
  "USE_CUDA=${USE_CUDA}"
  "JAX_CUDA_EXTRA=${JAX_CUDA_EXTRA:-cuda12}"
  "BOOTSTRAP_OFFLINE=${BOOTSTRAP_OFFLINE:-1}"
  "PLAYGROUND_REF=${PLAYGROUND_REF:-d886c80}"
  "PYTHON_BIN=${PYTHON_BIN:-python3}"
  "USE_TB=${USE_TB:-1}"
  "USE_WANDB=${USE_WANDB:-0}"
)

MEM_PRINT="${MEM:-<cluster-default>}"
echo "[submit-push] mode=${MODE} partition=${PARTITION} gpus=${GPUS} cpus=${CPUS_PER_TASK} mem=${MEM_PRINT} time=${TIME_LIMIT}"
echo "[submit-push] rough_ckpt=${ROUGH_CKPT}"
echo "[submit-push] script=${SBATCH_SCRIPT}"

mkdir -p "${ROOT_DIR}/logs"

SBATCH_ARGS=(
  "--partition=${PARTITION}"
  "--gres=gpu:${GPUS}"
  "--cpus-per-task=${CPUS_PER_TASK}"
  "--time=${TIME_LIMIT}"
  "--chdir=${ROOT_DIR}"
  "--export=$(IFS=,; echo "${EXPORT_VARS[*]}")"
)

if [ -n "${MEM}" ]; then
  SBATCH_ARGS+=("--mem=${MEM}")
fi

sbatch "${SBATCH_ARGS[@]}" "${SBATCH_SCRIPT}"
